const $=id=>document.getElementById(id);
const CASES={monthly:'The Phantom Monthly Payment',claim:'The Rusty Scratch',pos:'Terminal Betrayal',lift:'Stacker 13',sofa:'The Forbidden Sofa',inspection:'Inspector Incoming',oversized:'Compact Escalade',keys:'The Vanishing Key Ring'};
const ACH={first:'First Fire Out',evidence:'Eagle Eyes',noCheck:'Christine Approved',sofa:'Furniture Is Not Parking',tech:'Percussive Engineering Avoided',compact:'Physics Wins',keys:'Key Whisperer',calm:'Cool Under Pressure',speed:'Before Lunch?!',perfect:'Garage Legend'};
const LOC={office:{name:'Garage Division Office',cls:'office',open:true,travel:0,props:['desk','monitor','phone'],intro:['CHRISTINE','Six garages need you, an inspector is on the way, and somebody put a sofa in Brittany.'],hot:[['desk','Desk',8,60,49,30],['monitor','Computer',16,34,20,27],['phone','Phone',41,48,13,18]]},emerald:{name:'Emerald Garage',cls:'emerald',open:true,travel:12,props:['garage-door','booth','car'],intro:['CUSTOMER','Your attendant scratched my bumper last night!'],hot:[['car','Claim Vehicle',27,61,39,27],['booth','Booth',72,46,24,43]]},crystal:{name:'Crystal Garage',cls:'crystal',open:true,travel:12,props:['garage-door','booth','car'],intro:['MANAGER','The POS terminal and the computer have stopped speaking.'],hot:[['booth','POS Terminal',71,45,25,44],['car','Waiting Customer',28,61,39,27]]},liberty:{name:'Liberty Garage',cls:'liberty',open:true,travel:14,props:['lift','car'],intro:['SUPERVISOR','Stacker 13 stopped halfway up. There is, of course, a car on it.'],hot:[['lift','Stacker 13',8,30,60,60],['car','Trapped Vehicle',29,61,40,27]]},brittany:{name:'Brittany Garage',cls:'brittany',open:true,travel:13,props:['sofa','booth'],intro:['RICHIE','Why is there a sofa in my garage?'],hot:[['sofa','Mystery Sofa',13,66,52,26],['booth','Manager Booth',72,45,24,44]]},regent:{name:'Regent Garage',cls:'regent',open:true,travel:11,props:['rateboard','gate','car'],intro:['ATTENDANT','This gentleman says his Escalade is a compact. Also, the inspector called again.'],hot:[['rateboard','Rate Board',7,15,36,43],['gate','Gate',72,28,25,62],['car','Escalade',27,61,40,27]]},executive:{name:'Executive Office',cls:'executive',open:false,travel:16,props:['conference'],intro:['MR. H','Is everything ready for tonight?'],hot:[['conference','Conference Table',8,64,75,27]]}};
const defaultState=()=>({score:0,stress:15,min:478,loc:'office',verb:'WALK',selected:null,inv:['Coffee','Clipboard'],flags:{monthly:0,claim:0,pos:0,lift:0,sofa:0,inspection:0,oversized:0,keys:0,photo:0,claimFootage:0,posDiagnosed:0,liftTag:0,sofaDoc:0,rateChecked:0,keyClue:0},ach:[],log:[],started:false,sound:true,music:false,ending:false});
let S=defaultState();let audioCtx=null,musicTimer=null;
function fmtTime(){let h=Math.floor(S.min/60),m=S.min%60;return `${h%12||12}:${String(m).padStart(2,'0')} ${h<12?'AM':'PM'}`}
function completeCount(){return Object.keys(CASES).filter(k=>S.flags[k]).length}
function allDone(){return completeCount()===Object.keys(CASES).length}
function beep(freq=440,d=.06,type='square',vol=.025){if(!S.sound)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+d);o.stop(audioCtx.currentTime+d)}catch(e){}}
function sfx(kind){({click:()=>beep(520,.04),good:()=>{beep(660,.06);setTimeout(()=>beep(880,.08),70)},bad:()=>{beep(160,.12,'sawtooth',.035);shake()},travel:()=>beep(260,.05),ring:()=>{beep(760,.07);setTimeout(()=>beep(760,.07),120)},save:()=>{beep(500,.04);setTimeout(()=>beep(700,.05),55)}}[kind]||(()=>{}))()}
function toggleMusic(){S.music=!S.music;$('musicBtn').textContent=S.music?'♫✓':'♫';if(S.music){audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();let notes=[220,277,330,247,294,370,330,277],i=0;musicTimer=setInterval(()=>{if(!S.music)return;beep(notes[i++%notes.length],.16,'triangle',.012)},220)}else clearInterval(musicTimer);autosave()}
function shake(){const st=$('stage');st.classList.remove('screen-shake');void st.offsetWidth;st.classList.add('screen-shake')}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1400)}
function portrait(name){const map={RICHIE:'RI',CHRISTINE:'CG',CUSTOMER:'CU',MANAGER:'MG',SUPERVISOR:'SV',HECTOR:'HR',ATTENDANT:'AT','MR. H':'MH',INSPECTOR:'DC',NARRATOR:'NY'};$('portrait').textContent=map[name]||name.slice(0,2)}
function say(name,text,choices=[]){portrait(name);$('speaker').textContent=name;$('dialogueText').textContent=text;const c=$('choices');c.innerHTML='';choices.forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{sfx('click');fn()};c.appendChild(b)})}
function addLog(t){S.log.unshift(t);S.log=S.log.slice(0,20)}
function points(n,msg){S.score=Math.max(0,Math.min(800,S.score+n));addLog(`${n>=0?'+':''}${n} ${msg}`);n>=0?sfx('good'):sfx('bad');update()}
function stress(n,msg=''){S.stress=Math.max(0,Math.min(100,S.stress+n));if(msg)addLog(`${n>=0?'+':''}${n} stress: ${msg}`);if(S.stress>=100)return gameOver('RORY, YOU’RE IN CHARGE.','Your stress meter reached 100%. You handed Rory the clipboard and vanished into Manhattan.');update()}
function addItem(i){if(!S.inv.includes(i)){S.inv.push(i);toast(`Added: ${i}`);beep(620,.05)}update()}
function removeItem(i){S.inv=S.inv.filter(x=>x!==i);if(S.selected===i)S.selected=null;update()}
function achievement(k){if(S.ach.includes(k))return;S.ach.push(k);toast(`🏆 ${ACH[k]}`);beep(784,.08);setTimeout(()=>beep(988,.1),80);update()}
function caseDone(k,score,msg){if(S.flags[k])return;S.flags[k]=1;points(score,msg);achievement('first');if(allDone()){LOC.executive.open=true;if(S.stress<40)achievement('calm');if(S.min<720)achievement('speed');$('objective').textContent='Report to the executive office before 6:00 PM.';toast('Executive Office unlocked!')}autosave()}
function moveAvatar(x,y=12,cb){$('avatar').style.left=x+'%';$('avatar').style.bottom=y+'%';setTimeout(()=>cb&&cb(),500)}
function renderScene(){const l=LOC[S.loc],st=$('stage');st.className=`stage ${l.cls}`;$('sceneLabel').textContent=l.name;$('props').innerHTML=l.props.map(p=>`<div class="prop ${p}"></div>`).join('');const hs=$('hotspots');hs.innerHTML='';l.hot.forEach(([id,label,x,y,w,h])=>{const d=document.createElement('div');d.className='hotspot';d.dataset.label=label;Object.assign(d.style,{left:x+'%',top:y+'%',width:w+'%',height:h+'%'});d.onclick=e=>handleHotspot(id,label,e);hs.appendChild(d)});moveAvatar(S.loc==='office'?68:64,12);say(...l.intro)}
function handleHotspot(id,label,e){const x=Math.min(82,Math.max(5,(e.offsetX/e.currentTarget.offsetWidth*25)+(parseFloat(e.currentTarget.style.left)||40)));moveAvatar(x,12,()=>interact(id,label))}
function interact(id,label){if(S.verb==='WALK')return say('RICHIE',`You walk over to the ${label.toLowerCase()}. Thrilling management action.`);if(S.verb==='LOOK')return lookAt(id);if(S.verb==='TALK')return talkTo(id);if(S.verb==='TAKE')return takeThing(id);if(S.verb==='USE')return useOn(id)}
function lookAt(id){const key=`${S.loc}:${id}`;const lines={'office:desk':'A desk covered in paperwork. Somewhere beneath it is probably 2017.','office:monitor':'The accounting screen is open. One payment is wearing the wrong property code.','office:phone':'It rings with the confidence of somebody else’s emergency.','emerald:car':'A luxury sedan with a bumper scratch old enough to have a pension.','emerald:booth':'Camera monitor, claim forms, and an attendant pretending not to listen.','crystal:booth':'The terminal says CONNECTION FAILED. It looks smug about it.','liberty:lift':'A hydraulic stacker frozen halfway up. Safety lock engaged.','brittany:sofa':'Upholstered liability. Possibly sentient.','regent:rateboard':'Rates, oversize definitions, tax notices. The inspector’s favorite bedtime reading.','regent:car':'An Escalade. Calling it compact is an act of optimism.','executive:conference':'A conference table polished to a level of accountability you find threatening.'};say('RICHIE',lines[key]||`You examine the ${id}. It remains suspicious.`)}
function talkTo(id){if(S.loc==='emerald'&&id==='car')return emerald();if(S.loc==='crystal'&&id==='booth')return crystal();if(S.loc==='liberty'&&id==='lift')return liberty();if(S.loc==='brittany')return brittany();if(S.loc==='regent'&&id==='car')return oversized();if(S.loc==='regent'&&id==='rateboard')return inspection();if(S.loc==='office'&&id==='monitor')return monthly();if(S.loc==='office'&&id==='phone')return keysCase();if(S.loc==='executive')return finale();say('RICHIE','Nobody here has anything useful to say. A rare gift.')}
function takeThing(id){if(S.loc==='office'&&id==='phone')return say('RICHIE','Tempting, but taking the office phone would only make it portable.');if(S.loc==='brittany'&&id==='sofa'){points(-15,'Attempted to inventory a sofa');return say('RICHIE','Absolutely not. Furniture is not inventory.')}say('RICHIE',`You decide not to steal the ${id}. Leadership.`)}
function useOn(id){if(!S.selected)return say('RICHIE','Use what? Select an inventory item first.');useItem(S.selected,id)}
function useItem(item,target=null){if(item==='Coffee'){stress(-12,'Coffee');removeItem('Coffee');return say('RICHIE','That was not coffee. That was a temporary staffing increase.')}if(S.loc==='emerald'&&item==='Security Footage'&&(target==='car'||!target)){removeItem('Security Footage');achievement('evidence');caseDone('claim',55,'Resolved claim using entry footage');stress(-5);return say('RICHIE','The footage shows the scratch before the car entered. Case closed.')}if(S.loc==='crystal'&&item==='Spare Terminal Cable'&&(target==='booth'||!target)){removeItem(item);achievement('tech');caseDone('pos',60,'Restored POS communication');return say('MANAGER','It’s online! Customers can once again give us money.')}if(S.loc==='liberty'&&item==='Stacker Reset Card'&&(target==='lift'||!target)){removeItem(item);caseDone('lift',70,'Reset Stacker 13 safely');stress(-6);return say('SUPERVISOR','The lift is moving. Slowly, safely, and expensively.')}if(S.loc==='brittany'&&item==='Camera'&&(target==='sofa'||!target)){S.flags.photo=1;addItem('Sofa Photo');return say('RICHIE','Photo taken. Evidence first, furniture removal second.')}if(S.loc==='brittany'&&item==='Removal Order'&&S.flags.photo){removeItem(item);caseDone('sofa',65,'Removed prohibited furniture');achievement('sofa');return say('HECTOR','The sofa has left the building.')}if(S.loc==='regent'&&item==='Current Rate Sheet'&&target==='rateboard'){S.flags.rateChecked=1;return say('RICHIE','The posted rate sheet and required notices match. The inspector will have to find a hobby.')}if(S.loc==='regent'&&item==='Oversize Measuring Card'&&target==='car'){removeItem(item);achievement('compact');caseDone('oversized',50,'Measured the “compact” Escalade');return say('CUSTOMER','So... oversized?',[['Yes. Physics remains undefeated.',()=>say('CUSTOMER','Fine. Put it on the bill.')]])}if(S.loc==='office'&&item==='Key Tag Photo'&&target==='phone'){removeItem(item);achievement('keys');caseDone('keys',55,'Located missing key ring');return say('CHRISTINE','Found them. They were hanging on the wrong numbered hook. Of course they were.')}say('RICHIE',`${item} does not solve this particular disaster.`)}
function emerald(){if(S.flags.claim)return say('CUSTOMER','So the scratch was already there?');say('CUSTOMER','Your attendant scratched my bumper last night!',[['Review entry footage before accepting liability.',()=>{S.flags.claimFootage=1;addItem('Security Footage');points(10,'Requested evidence first');say('RICHIE','I’ll compare the entry footage to the claim.')}],['Promise reimbursement immediately.',()=>{points(-25,'Accepted liability without investigation');stress(10,'Premature promise');say('CHRISTINE','No. We are going to investigate like adults.')}],['Point out the rust.',()=>{points(4,'Observed ancient rust');stress(7,'Customer disliked archaeology');say('CUSTOMER','ARE YOU CALLING ME A LIAR?')}]] )}
function crystal(){if(S.flags.pos)return say('MANAGER','Everything is synced. I have forgiven the terminal.');say('MANAGER','The POS and terminal stopped communicating.',[['Inspect the physical connection.',()=>{S.flags.posDiagnosed=1;addItem('Spare Terminal Cable');points(10,'Diagnosed before rebooting');say('RICHIE','The cable is failing intermittently. Use the spare.')}],['Reboot everything until morale improves.',()=>{S.min+=18;points(-8,'Reboot roulette');stress(10,'Printer also stopped working');say('MANAGER','Now the receipt printer is blinking too.')}],['Put up a CASH ONLY sign.',()=>{points(-18,'Invented a compliance problem');say('RICHIE','No. This is a garage, not a yard sale.')}]] )}
function liberty(){if(S.flags.lift)return say('SUPERVISOR','Stacker 13 is behaving itself. For now.');say('SUPERVISOR','Stacker 13 stopped halfway up.',[['Read the equipment tag and safety status.',()=>{S.flags.liftTag=1;addItem('Stacker Reset Card');points(10,'Matched equipment to reset procedure');say('RICHIE','Safety lock first. Correct reset sequence second. Nobody improvises with two tons of car.')}],['Hit the green button harder.',()=>{points(-20,'Attempted percussive engineering');stress(12,'Lift remains stuck');say('SUPERVISOR','It remains emotionally unavailable.')}]] )}
function brittany(){if(S.flags.sofa)return say('HECTOR','No more furniture. I have learned a permanent lesson.');say('HECTOR','I was going to call you about the sofa.',[['Photograph it and issue immediate removal.',()=>{addItem('Camera');addItem('Removal Order');S.flags.sofaDoc=1;points(10,'Documented prohibited storage');say('RICHIE','Get it out today. Furniture plus garage equals bed bug roulette.')}],['Sit down for one minute.',()=>{points(-30,'Sat on mystery garage furniture');gameOver('BED BUG PROTOCOL','The sofa has won. Somewhere, an exterminator senses a disturbance in the force.')}],['Pretend you never saw it.',()=>{stress(14,'Furniture continues existing');points(-10,'Ignored obvious liability');say('NARRATOR','The sofa quietly gains confidence.')}]] )}
function monthly(){if(S.flags.monthly)return say('CHRISTINE','That account is corrected. Wrong property code.');say('CHRISTINE','A monthly parker insists he paid. The ledger says otherwise.',[['Search by amount and date across properties.',()=>{caseDone('monthly',70,'Found payment on wrong property code');achievement('noCheck');say('CHRISTINE','There it is. Wrong property. I fixed it. Eagle eyes.')}],['Tell the customer to pay again.',()=>{points(-25,'Attempted double collection');stress(8,'Customer understandably objected');say('CHRISTINE','We are absolutely not doing that.')}]] )}
function inspection(){if(S.flags.inspection)return say('ATTENDANT','Inspector left. Disappointingly uneventful.');say('ATTENDANT','The inspector is five minutes away.',[['Compare posted signs to the current rate sheet.',()=>{addItem('Current Rate Sheet');S.flags.rateChecked=1;points(12,'Verified current postings');caseDone('inspection',65,'Passed inspection readiness check');say('RICHIE','Everything is current. Nobody print a sign in Comic Sans.')}],['Hide the rate board.',()=>{points(-30,'Tried to hide required signage');stress(15,'Inspector noticed movement');say('INSPECTOR','Why are you carrying that sign?')}]] )}
function oversized(){if(S.flags.oversized)return say('ATTENDANT','The Escalade owner has accepted geometry.');say('CUSTOMER','This is basically a compact SUV.',[['Measure it using the posted criteria.',()=>{addItem('Oversize Measuring Card');points(8,'Chose measurement over debate');say('RICHIE','Let’s use numbers. Numbers have less patience than I do.')}],['Agree to avoid an argument.',()=>{points(-15,'Redefined compact vehicle');say('ATTENDANT','Should I also mark the Suburban as a bicycle?')}]] )}
function keysCase(){if(S.flags.keys)return say('CHRISTINE','The missing key ring is back where it belongs.');sfx('ring');say('MANAGER ON PHONE','We can’t find the key ring for a monthly vehicle. Customer is waiting.',[['Ask for a photo of the key board.',()=>{addItem('Key Tag Photo');points(8,'Requested visual evidence');say('RICHIE','Send me the key board. Check neighboring hooks, not just the matching number.')}],['Tell them to keep looking.',()=>{stress(6,'Unstructured key search');say('MANAGER ON PHONE','We have been doing that for twenty minutes.')}]] )}
function finale(){if(!allDone())return say('MR. H','Come back when everything is actually ready.');if(S.ending)return;S.ending=true;let bonus=0;if(S.min<1080)bonus+=50;if(S.stress<45)bonus+=40;S.score=Math.min(800,S.score+bonus);if(S.score>=760)achievement('perfect');const rank=S.score>=760?'LEGENDARY GARAGE BOSS':S.score>=650?'VICE PRESIDENT OF CHAOS':S.score>=520?'MANHATTAN PARKING PRO':S.score>=380?'SOLID OPERATOR':'SURVIVOR OF MONDAY';modal(rank,`<div class="ending-rank">${rank}</div><p>The POS is online, the lift is moving, the claim is closed, the monthly payment is found, the inspector is bored, the Escalade has accepted geometry, the keys are back, and the sofa has been banished.</p><div class="statline"><span>Final score</span><b>${S.score} / 800</b></div><div class="statline"><span>Stress</span><b>${S.stress}%</b></div><div class="statline"><span>Time</span><b>${fmtTime()}</b></div><div class="statline"><span>Achievements</span><b>${S.ach.length}/${Object.keys(ACH).length}</b></div><p><b>MR. H:</b> “Good. One more thing...”</p><p>The phone rings.</p><h3>CHAPTER 2: THE UNITED NATIONS IS COMING</h3>`,[['Continue Exploring',()=>hideModal()],['Start New Game',()=>newGame()]])}
function travel(k){if(!LOC[k].open)return;S.loc=k;S.min+=LOC[k].travel;sfx('travel');renderScene();update();autosave()}
function setVerb(v){S.verb=v;document.querySelectorAll('[data-verb]').forEach(b=>b.classList.toggle('active',b.dataset.verb===v));if(v!=='USE')S.selected=null;update()}
function update(){$('time').textContent=fmtTime();$('score').textContent=S.score;$('stress').textContent=S.stress;$('stressBar').style.width=S.stress+'%';if(allDone())$('objective').textContent='Report to the executive office before 6:00 PM.';else $('objective').textContent=`Resolve garage emergencies (${completeCount()}/${Object.keys(CASES).length})`;$('inventory').innerHTML='';S.inv.forEach(i=>{const b=document.createElement('button');b.textContent=i;b.classList.toggle('selected',S.selected===i);b.onclick=()=>{if(S.verb==='USE'){S.selected=S.selected===i?null:i;toast(S.selected?`Selected: ${i}`:'Selection cleared');update()}else useItem(i)};$('inventory').appendChild(b)});$('invCount').textContent=S.inv.length;$('miniMap').innerHTML='';Object.entries(LOC).forEach(([k,l])=>{const b=document.createElement('button');b.className='map-node'+(k===S.loc?' current':'')+(!l.open?' locked':'');b.textContent=(l.open?'':'🔒 ')+l.name;b.onclick=()=>l.open&&travel(k);$('miniMap').appendChild(b)});$('caseBoard').innerHTML='';Object.entries(CASES).forEach(([k,n])=>{const d=document.createElement('div');d.className='case '+(S.flags[k]?'done':'open');d.textContent=(S.flags[k]?'✓ ':'○ ')+n;$('caseBoard').appendChild(d)});$('achievements').innerHTML='';Object.entries(ACH).forEach(([k,n])=>{const d=document.createElement('div');d.className='ach '+(S.ach.includes(k)?'unlocked':'');d.textContent=(S.ach.includes(k)?'🏆 ':'◇ ')+n;$('achievements').appendChild(d)});$('achCount').textContent=S.ach.length;$('soundBtn').textContent=S.sound?'🔊':'🔇';$('musicBtn').textContent=S.music?'♫✓':'♫'}
function autosave(){try{localStorage.setItem('garageBossSave',JSON.stringify(S))}catch(e){}}
function saveGame(){autosave();sfx('save');toast('Game saved locally')}
function loadGame(){try{const raw=localStorage.getItem('garageBossSave');if(!raw)return toast('No save found');const data=JSON.parse(raw);S={...defaultState(),...data,flags:{...defaultState().flags,...data.flags}};LOC.executive.open=allDone();renderScene();update();hideModal();toast('Save loaded')}catch(e){toast('Save could not be loaded')}}
function newGame(){S=defaultState();LOC.executive.open=false;localStorage.removeItem('garageBossSave');hideModal();renderScene();update();intro()}
function gameOver(t,b){modal(t,`<p>${b}</p><div class="statline"><span>Score</span><b>${S.score}/800</b></div>`,[['Load Save',()=>loadGame()],['Try Monday Again',()=>newGame()]])}
function modal(t,html,actions=[['Continue',()=>hideModal()]]){$('modalTitle').textContent=t;$('modalBody').innerHTML=html;$('modalActions').innerHTML='';actions.forEach(([lab,fn])=>{const b=document.createElement('button');b.textContent=lab;b.onclick=fn;$('modalActions').appendChild(b)});$('modal').classList.add('show')}
function hideModal(){$('modal').classList.remove('show')}
function intro(){modal('MONDAY, 7:58 AM',`<p>Richie walks into Garage Division headquarters carrying coffee.</p><p>The phone is already ringing. Christine is staring at a report like it personally insulted her.</p><p><b>CHRISTINE:</b> “Richie, before you answer that...”</p><p><b>RICHIE:</b> “What?”</p><p><b>CHRISTINE:</b> “We have a problem.”</p><p><b>RICHIE:</b> “Which garage?”</p><p><b>CHRISTINE:</b> “Yes.”</p><p><b>OBJECTIVE:</b> Resolve eight emergencies before the evening executive review.</p>`,[['Start Chapter 1',()=>{S.started=true;hideModal();renderScene();update();autosave()}],['Load Saved Game',()=>loadGame()]])}
function mapModal(){let html='<div class="big-map">';Object.entries(LOC).forEach(([k,l])=>html+=`<button data-map="${k}" ${l.open?'':'disabled'}>${l.open?'':'🔒 '}${l.name}<br><small>${k===S.loc?'CURRENT LOCATION':''}</small></button>`);html+='</div>';modal('MANHATTAN GARAGE MAP',html,[['Close',()=>hideModal()]]);document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{hideModal();travel(b.dataset.map)})}
function help(){modal('HOW TO PLAY',`<p><b>WALK</b> moves Richie to an object. <b>LOOK</b> examines it. <b>TALK</b> starts conversations. <b>TAKE</b> attempts to collect it. <b>USE</b> combines an inventory item with a scene object.</p><p>On mobile, select <b>USE</b>, tap an inventory item, then tap the object in the scene. Travel using the Manhattan Map. The game autosaves after major progress, and the 💾 button saves manually.</p><p>Bad decisions can cost points, time, or stress. Some are worth trying anyway.</p>`,[['Got it',()=>hideModal()]])}
document.querySelectorAll('[data-verb]').forEach(b=>b.onclick=()=>setVerb(b.dataset.verb));$('mapBtn').onclick=mapModal;$('saveBtn').onclick=saveGame;$('loadBtn').onclick=loadGame;$('helpBtn').onclick=help;$('soundBtn').onclick=()=>{S.sound=!S.sound;update();autosave()};$('musicBtn').onclick=toggleMusic;window.addEventListener('beforeunload',autosave);renderScene();update();intro();